version: '3.8'

services:

  web:
    build: ./Service
    ports:
      - 8000:8000
    command: uvicorn app:app --host 0.0.0.0 --reload
    volumes:
      - ./Service:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      
      
  worker:
    build: ./Service
    command: celery -A celery_task_app.worker worker -l info
    volumes:
      - ./Service:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      
      
  redis:
    image: redis:6-alpine